// Generated by CoffeeScript 1.6.3
(function() {
  CodeMirror.defineMode("cirru", function() {
    return {
      startState: function() {
        return {
          head: true
        };
      },
      token: function(stream, state) {
        console.log(stream, state);
        if (stream.match("$")) {
          state.head = true;
          return "dollar";
        } else if (stream.match(/^[^\$\"\s\(\)][^\"\s\(\)]*/)) {
          if (state.head) {
            state.head = false;
            return "word-func";
          } else {
            return "word";
          }
        } else if (stream.match(/^"([^\\\"]|(\\.))*\"/)) {
          if (state.head) {
            state.head = false;
            return "string-func";
          } else {
            return "string";
          }
        } else if (stream.match("(")) {
          state.head = true;
          return "bracket";
        } else if (stream.match(")")) {
          state.head = false;
          return "bracket";
        } else if (stream.match("\n")) {
          console.log("start of line");
          return state.head = true;
        } else {
          stream.next();
          return null;
        }
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=cirru.map
*/
